server:
  port: 8089

github:
  client:
    id: 6b3969cc18b4194946c3
    secret: b0ce0f3267ab12941c6eec2cb8604d92d92d3058
  redirect:
    uri: http://localhost:8089/callback

ucloud:
  ufile:
    public-key: TOKEN_15eb8367-8fd3-4653-b769-1959cb22814a
    private-key: 5eef574c-e734-488e-9f24-40be55f262a5
    bucket-name: liaoliao
    region: cn-bj
    suffix: ufileos.com
    expires: 315360000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: allen.community.mapper
  mapper-locations: classpath:mapper/*.xml

logging:
  # log文件存放地址 项目根目录下
  file: logs/community.log
  level:
    root: info
    allen:
      community:
        mapper: debug

